artist:
  name: alien people
  tagline: we come from mars
  seo_title: Alien People Band
  seo_description: Band from Guildford. Playing rock and roll music sent to us by aliens
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: alienpeopleofficial@gmail.com

social:
  - name: Instagram
    url: https://www.instagram.com/alienpeopleofficial/
  - name: Youtube
    url: https://youtube.com
  - name: Spotify
    url: https://spotify.com

site_language: en
